{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7bc6cc0c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(\"C:\\\\Users\\\\aitma\\\\Downloads\\\\Exrcice validation croisée\\\\blood_transfusion.csv\")\n",
    "X = df.drop(columns=\"Class\")\n",
    "Y = df[\"Class\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "5280bb32",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Recency</th>\n",
       "      <th>Frequency</th>\n",
       "      <th>Monetary</th>\n",
       "      <th>Time</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2</td>\n",
       "      <td>50</td>\n",
       "      <td>12500</td>\n",
       "      <td>98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "      <td>3250</td>\n",
       "      <td>28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1</td>\n",
       "      <td>16</td>\n",
       "      <td>4000</td>\n",
       "      <td>35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2</td>\n",
       "      <td>20</td>\n",
       "      <td>5000</td>\n",
       "      <td>45</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>1</td>\n",
       "      <td>24</td>\n",
       "      <td>6000</td>\n",
       "      <td>77</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Recency  Frequency  Monetary  Time\n",
       "0        2         50     12500    98\n",
       "1        0         13      3250    28\n",
       "2        1         16      4000    35\n",
       "3        2         20      5000    45\n",
       "4        1         24      6000    77"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X.head() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2be9dcef",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0        donated\n",
       "1        donated\n",
       "2        donated\n",
       "3        donated\n",
       "4    not donated\n",
       "Name: Class, dtype: object"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "Y.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "8d86bfdc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "L'accuracy moyenne est 0.750 +/- 0.030\n"
     ]
    }
   ],
   "source": [
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.pipeline import make_pipeline\n",
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.model_selection import cross_val_score, KFold\n",
    "\n",
    "#création une régression logistque\n",
    "modèle = make_pipeline(StandardScaler(), LogisticRegression())\n",
    "\n",
    "\n",
    "# Validation croisé avec stratification\n",
    "cv = StratifiedKFold(n_splits=3)\n",
    "# on  Utilise explicitement le paramètre de scoring de cross_val_score\n",
    "rs = cross_val_score(modèle, X, Y, cv=cv,scoring='accuracy')\n",
    "\n",
    "print(f\"L'accuracy moyenne est \"\n",
    "      f\"{rs.mean():.3f} +/- {rs.std():.3f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0716c5e7",
   "metadata": {},
   "source": [
    "on refait l'expérimentation en calculant balanced_accuracy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1c2edfd9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "L'accuracy moyenne est 0.597 +/- 0.088\n"
     ]
    }
   ],
   "source": [
    "# on  Utilise explicitement le paramètre de scoring de cross_val_score 'balanced_accuracy'\n",
    "rs = cross_val_score(modèle, X, Y, cv=cv,scoring='balanced_accuracy')\n",
    "\n",
    "print(f\"L'accuracy moyenne est \"\n",
    "      f\"{rs.mean():.3f} +/- {rs.std():.3f}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6486322c",
   "metadata": {},
   "source": [
    "alors l'accuracy c'est le nombre des predictions correctes sur le nombre de toutes les observations\n",
    "mais balanced_accuracy est  la somme des nombres des predictions correctes par chaque classe multiplié par l\"inverse de nombre de classe  \n",
    "\n",
    "dans notre dataset est : 1/2*((correcte donated prediction / nb of donated )+(correcte undonated prediction / nb of undonated prediction))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "cd4b6aed",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1662, in precision_score\n",
      "    zero_division=zero_division)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1465, in precision_recall_fscore_support\n",
      "    pos_label)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_classification.py\", line 1286, in _check_set_wise_labels\n",
      "    f\"pos_label={pos_label} is not a valid label. It \"\n",
      "ValueError: pos_label=1 is not a valid label. It should be one of ['donated', 'not donated']\n",
      "\n",
      "  UserWarning,\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "model = LogisticRegression()\n",
    "try:\n",
    "    scores = cross_val_score(model, X, Y, cv=10, scoring=\"precision\")\n",
    "except ValueError as exc:\n",
    "    print(exc)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "2fc4c3e4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "make_scorer(precision_score, pos_labels=donated)\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import make_scorer\n",
    "from sklearn.metrics import precision_score\n",
    "scorer=make_scorer(precision_score,pos_labels=\"donated\")\n",
    "print(scorer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "f9973d5d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[nan nan nan nan nan nan nan nan nan nan]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n",
      "C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:700: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 687, in _score\n",
      "    scores = scorer(estimator, X_test, y_test)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 88, in __call__\n",
      "    *args, **kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\metrics\\_scorer.py\", line 243, in _score\n",
      "    **self._kwargs)\n",
      "  File \"C:\\Users\\aitma\\anaconda3\\envs\\env_etl\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 63, in inner_f\n",
      "    return f(*args, **kwargs)\n",
      "TypeError: precision_score() got an unexpected keyword argument 'pos_labels'\n",
      "\n",
      "  UserWarning,\n"
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "model = LogisticRegression()\n",
    "\n",
    "scores = cross_val_score(model, X, Y, cv=10, scoring=scorer)\n",
    "print(scores)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "0fe2a605",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'fit_time': array([0.03399682, 0.0260005 , 0.02099967, 0.0179863 , 0.02400279,\n",
       "        0.02001905, 0.02369142, 0.0199995 , 0.02198577, 0.02497768]),\n",
       " 'score_time': array([0.00799584, 0.00401664, 0.00300002, 0.00399876, 0.00400066,\n",
       "        0.00299954, 0.00401354, 0.00399971, 0.00401402, 0.00402212]),\n",
       " 'test_accuracy': array([0.77333333, 0.78666667, 0.76      , 0.76      , 0.74666667,\n",
       "        0.76      , 0.77333333, 0.78666667, 0.77027027, 0.77027027]),\n",
       " 'test_balanced_accuracy': array([0.8128655 , 0.55555556, 0.5       , 0.5       , 0.49122807,\n",
       "        0.5       , 0.66081871, 0.55555556, 0.5       , 0.5       ])}"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.model_selection import cross_validate\n",
    "scoring = [\"accuracy\", \"balanced_accuracy\"]\n",
    "\n",
    "scores = cross_validate(model, X, Y, cv=10, scoring=scoring)\n",
    "scores"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "2a4c19c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "metrics = pd.DataFrame(\n",
    "    [scores[\"test_accuracy\"], scores[\"test_balanced_accuracy\"]],\n",
    "    index=[\"Accuracy\", \"Balanced accuracy\"]\n",
    ").T"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "582ce73f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXoAAAEICAYAAABRSj9aAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAd0klEQVR4nO3de5RcZZ3u8e9jhxCUW0KCB0JMIoahJShCi6LowIxg9CwIDooJookG8cwycfSIc9B4ZmIcFNfSQQdQuaqo0wFROa0zc2Icg5zmoqlIgFwEYlCSjEiTCxclkoTf+WO/HXaK6q7qpLur+83zWatWV7373Xv/9q5dT+16d3W3IgIzM8vXi5pdgJmZDSwHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz01hSSZkvqHG7L3lOSbpN0YbPr2NdI+pSk65pdR7M56G3IkTRJUkh6Ot3+IOmrkvZrdm02NEg6TdKGev0i4nMRsc+/wTrohzkVcn0eD42IA4HjgVOADze5nixJGtHsGgZCrtu1J3INiEEl6RJJv5H0lKTVkt5RNf2DktaUpp+Y2idI+oGkLkmbJF2Z2hdI+k5p/u4z3BHp8W2SLpV0B/An4OWS3l9axzpJH6qqYbqkFZKeTLVOk/QuScur+v1PSf+nh+3scR3dZ1iSPi7pMUm/l/T+0vTDJHWk9f8SOLrR/RsRjwFLgFc2us+r6v6KpPVp3cslvak0bYGkmyXdmJa1SlJbaXrN5yhN+0DaH1skLZY0sTTtDEm/lvREmke91HeypLskbU377UpJI0vTj5O0RNLm9OnmU6m9JQ1NdO+H5ane3Y6X1HfX0JGKoa07JF0uaROwQNLRkn6WtvFxSd+VdGhv+0HSyFTT8aV+h0v6k6RxNbazvN6t6Rh6Q2pfn46bWaX++0v6oqRH0nZ/XdIBkl4C/AdwpJ7/1Hdkei5vkfQdSU8Cs/XC19Kpku5M618vaXZqf3s6jp6StFHSxT09X8NSRPi2lzfgXcCRFG+c7wb+CBxRmrYReC3Fi/0VwESgBbgXuBx4CTAKODXNswD4Tmn5k4AARqTHtwGPAMcBI4D9gP9OEZ4C/pLiDeDE1P9k4AngjFTjeOBYYH9gM9BaWtc9wLk9bGdv6zgN2AEsTPW8PU0fnaYvAm5O2zo17ZPOHtZTvb1Hpn31gQb3+ezysoELgMPSvvo48CgwqrSvt6V6W4DPA3enab09R9OBtUBrWu6ngTvTtLHAU8A70774WNo3F/awvScBr0/LmQSsAT6aph0E/D7VPSo9fl2a9gngfuAv0nPy6rSdu+2/0jFzYWn/7ADmpXUeQHFcnpGOiXHA7cCXG9gPXwW+UFrP3wE/6mE7u9f7/rTMf6I4jq9K6z0z7bcDU//LgQ5gTNruHwGfLx1vG6qWvwDYDpxDcVwcQOm1RPG6ewqYmZ6Xw4AT0rTfA29K90eTjutcbk0vIMcbsAKYnu4vBv6uRp9TgK7yi7E0bdfBmR7v9sJNL9qFdWq4tXu9wNXA5T30+xpwabp/HLAF2L/B7Syv4zTgmapweYwiwFrSC/DY0rTPUT/ot6ZbAHcCBze4z2f3tOw0fQvw6tK+/mlp2iuBZxp4jv4DmFN6/CKKN7aJwPtIbxZpmoAN9BD0NZb9UeCH6f5M4J4e+j3Qvc097L/egv6ROjWc073eOvvhdRRhrfS4ApzXwzJnAw+VHh+f6nxpqW0TcELaZ38Ejq56zTxcOt5qBf3tPb2WgE9279catT0CfKi3Y2w43zx00w8kvU/FsMhWSVspzljHpskTgN/UmG0C8LuI2LGHq11fVcPbJN2dPkpvpThDrVcDwLeA8yUJeC9wc0T8uVbHOusA2FS1PX8CDqQ4QxxRVfPvGtjGsRFxKPBi4A6KN83uWnrb59V1X5yGWJ5IfQ+p6vtoVc2j0rBHb8/RROArpfVvpgin8RSfNHZtaxRJsr7GMrrrO0bSjyU9moYcPkdjz11v0+qpPn5eKmlRGrZ4EvhOVQ0190NE/IJin50m6ViKTwYdvaz3D6X7z6RlVLd1HzMvBpaX9vH/Te0Nb1eV3vbXuRTH8+8k/VzSKXXWM6w46PdSGpe9FpgLHJaCaSXPj8mup/Z49HrgZap9weiPFAd5t/9Wo8+uPzsqaX/g+8AXKc6ODgX+vYEaiIi7gWeBNwHnA9+u1a+BdfSmi+Ij+4RS28samK+7xmeAbwKvlzS2gX1ervtNwN8D51EMIx1KMYzVSN29PUfrgQ9FxKGl2wERcSfFMMCubU1vohNqLKPb14BfA1Mi4mDgU+z+3L28l/pqPa9/TD97O4aq/2zt51Lb8amGC6pq6Gk/QHGycAHFicItEbGth3598ThF6B9X2r+HRHFxvlb91GmH3l8HyyJiOnA4xSfVm/es7KHJQb/3XkJxcHVBccGS4uyy23XAxZJOUuEVKah+SREIl0l6iaRRkt6Y5lkBvFnSyyQdQvGRszcjKcY4u4Adkt5GMd7Z7Xrg/ZL+WtKLJI1PZ1/dbgSuBLZHRE/fP6+3jh5FxE7gBxQX/V4s6ZXArDqz7ZLeZN5Lcea9ifr7vOwgijeZLmCEpH8ADm5w1b09R18HPinpuFTDIZLelab9G3CcpL9J4fgRar9Zl2t8Eng6PS9/W5r2Y+AISR9NFycPkvS6NO064LOSpqRj61WSDouILoprIBeouGD7Aepf/D4IeBp4QtJ4ivH/RvYDFGf/76AI+xvrrKchEfEcxZv55ZIOB0jH7VtTlz8Ah6XXR6O+C7xF0nmSRqj4gsAJKi4qv0fSIRGxneK5eK4/tmOocNDvpYhYDXwJuIvi4DueYpihe/r3gEuBf6W4EHQrMCaF31kUH3UfoRjDfXeaZwlwE3AfsJzixd5bDU9RhMnNFOPP51P6+BwRv6S4AHY5xdnszymGHrp9myIov0MP6q2jAXMpPpI/SnF2/o0G5tkq6WmK/XoKcHYUet3nVRZTfOR/kGK4aBu9f7zfpc5z9EPgC8CiNNSxEnhbmvY4xcXiyyjemKb0Uh/AxRT78ymKcLupVMNTFBdJz6LYdw8Bp6fJ/0zxfPyEIpyup7gACfBBirDeRHHt5c46m/sZ4ESK4+PfKN6Y6+6HNH098CuKN9//V2c9ffG/KC5435328U8pLjwTEb8G2oF1aWjnyHoLi4hHKIZnPk4x1LaC4gI2FCcSv03r+R/Ae/pxO5qu+wKK7cMkHUBx4fTEiHio2fXY8CPpBuC/IuLTza7FXsi/UGBQDBUsc8jbnpA0Cfgb4DVNLsV64KDfx0n6LcVFt3OaW4kNR5I+S/F7Ap+PiIebXY/V5qEbM7PM+WKsmVnmhtzQzdixY2PSpEnNLsPMbFhZvnz54xFR8xfKhlzQT5o0iUql0uwyzMyGFUk9/ra5h27MzDLnoDczy5yD3swscw56M7PMOejNzDLnoDezQdfe3s7UqVNpaWlh6tSptLe3N7ukrA25r1eaWd7a29uZP38+119/PaeeeiqdnZ3MmTMHgJkzZza5ujwNuT+B0NbWFv4evVm+pk6dyhVXXMHpp5++q23p0qXMmzePlStXNrGy4U3S8ohoqznNQW9mg6mlpYVt27ax33777Wrbvn07o0aNYufOnU2sbHjrLeg9Rm9mg6q1tZXOzt3/kVlnZyetra1Nqih/DnozG1Tz589nzpw5LF26lO3bt7N06VLmzJnD/Pnzm11atnwx1swGVfcF13nz5rFmzRpaW1u59NJLfSF2AHmM3swsA3s9Ri9pmqQHJK2VdEmN6S+TtFTSPZLuk/T20rRPpvkeKP0HdzMzGyR1h24ktQBXUfwn+g3AMkkdEbG61O3TwM0R8TVJrwT+HZiU7s+g+C/0RwI/lXRM+q/yZmY2CBo5oz8ZWBsR6yLiWWARML2qTwAHp/uHAP+V7k8HFkXEn9P/k1yblmdmZoOkkaAfD6wvPd6Q2soWABdI2kBxNj+vD/Mi6SJJFUmVrq6uBks3M7NG9NfXK2cC34yIo4C3A9+W1PCyI+KaiGiLiLZx42r+JywzM9tDjXy9ciMwofT4qNRWNgeYBhARd0kaBYxtcF4zMxtAjZx1LwOmSJosaSTFxdWOqj6PAH8NIKkVGAV0pX4zJO0vaTIwBfhlfxVvZmb11T2jj4gdkuYCi4EW4IaIWCVpIVCJiA7g48C1kj5GcWF2dhRf0F8l6WZgNbAD+LC/cWNmNrj8C1NmZhnwHzUzM9uHOejNzDLnP2qWCanv8wyxUTszGyAO+kz0FNqSA91sX+ehGzOzzDnozcwy56A3M8ucg97MLHMOejOzzDnozcwy56A3M8ucg36YGTOm+G58ozfoW3+pWIeZ5cNBP8xs2ZLHOsxs8Pg3Y4ehgf5N1z35cwpmNnT5jN7MLHMOejOzzDnozcwy56A3M8ucg97MLHP+1s0wNNDfihk9emCXb2aDy0E/zPT1q5X+xyNm5qEbM7PMNRT0kqZJekDSWkmX1Jh+uaQV6fagpK2laTtL0zr6sXYzM2tA3aEbSS3AVcAZwAZgmaSOiFjd3SciPlbqPw94TWkRz0TECf1WsZmZ9UkjZ/QnA2sjYl1EPAssAqb30n8m0N4fxZmZ2d5rJOjHA+tLjzektheQNBGYDPys1DxKUkXS3ZLO6WG+i1KfSldXV2OVm5lZQ/r7YuwM4JaI2FlqmxgRbcD5wJclHV09U0RcExFtEdE2bty4fi7JzGzf1kjQbwQmlB4fldpqmUHVsE1EbEw/1wG3sfv4vfWTPfl79Ga2b2gk6JcBUyRNljSSIsxf8O0ZSccCo4G7Sm2jJe2f7o8F3gisrp7X9l5E329mtm+o+62biNghaS6wGGgBboiIVZIWApWI6A79GcCiiN0ipBW4WtJzFG8ql5W/rWNmZgNPMcRO7dra2qJSqTS7DDOzYUXS8nQ99AX8m7FmZplz0JuZZc5Bb2aWOQe9mVnmHPRmZplz0JuZZc5Bb2aWOQe9mVnmHPRmZplz0JuZZc5Bb2aWOQe9mVnmHPRmZplz0JuZZc5Bb2aWOQe9mVnmHPRmZplz0JuZZc5Bb2aWOQe9mVnmHPRmZplrKOglTZP0gKS1ki6pMf1ySSvS7UFJW0vTZkl6KN1m9WPtZmbWgBH1OkhqAa4CzgA2AMskdUTE6u4+EfGxUv95wGvS/THAPwJtQADL07xb+nUrzMysR42c0Z8MrI2IdRHxLLAImN5L/5lAe7r/VmBJRGxO4b4EmLY3BZuZWd80EvTjgfWlxxtS2wtImghMBn7W13nNzGxg9PfF2BnALRGxsy8zSbpIUkVSpaurq59LMjPbtzUS9BuBCaXHR6W2Wmbw/LBNw/NGxDUR0RYRbePGjWugJDMza1QjQb8MmCJpsqSRFGHeUd1J0rHAaOCuUvNi4ExJoyWNBs5MbWZmNkjqfusmInZImksR0C3ADRGxStJCoBIR3aE/A1gUEVGad7Okz1K8WQAsjIjN/bsJZmbWG5VyeUhoa2uLSqXS7DLMzIYVScsjoq3WNP9mrJlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZkNuvb2dqZOnUpLSwtTp06lvb29/ky2x+r+K0Ezs/7U3t7O/Pnzuf766zn11FPp7Oxkzpw5AMycObPJ1eXJ/0rQzAbV1KlTueKKKzj99NN3tS1dupR58+axcuXKJlY2vPX2rwQd9GY2qFpaWti2bRv77bffrrbt27czatQodu7c2cTKhjf/z1gzGzJaW1vp7Ozcra2zs5PW1tYmVZQ/B72ZDar58+czZ84cli5dyvbt21m6dClz5sxh/vz5zS4tWw1djJU0DfgK0AJcFxGX1ehzHrAACODeiDg/te8E7k/dHomIs/uhbjMbprovuM6bN481a9bQ2trKpZde6guxA6juGL2kFuBB4AxgA7AMmBkRq0t9pgA3A38VEVskHR4Rj6VpT0fEgY0W5DF6M7O+29sx+pOBtRGxLiKeBRYB06v6fBC4KiK2AHSHvJmZNV8jQT8eWF96vCG1lR0DHCPpDkl3p6GebqMkVVL7ObVWIOmi1KfS1dXVl/rNzKyO/vqFqRHAFOA04CjgdknHR8RWYGJEbJT0cuBnku6PiN+UZ46Ia4BroBi66aeazMyMxs7oNwITSo+PSm1lG4COiNgeEQ9TjOlPAYiIjennOuA24DV7WbOZmfVBI0G/DJgiabKkkcAMoKOqz60UZ/NIGksxlLNO0mhJ+5fa3wisxszMBk3doZuI2CFpLrCY4uuVN0TEKkkLgUpEdKRpZ0paDewEPhERmyS9Abha0nMUbyqXlb+tY2ZmA89/AsHMLAP+EwhmZvswB72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYaCnpJ0yQ9IGmtpEt66HOepNWSVkn611L7LEkPpdus/irczMwaM6JeB0ktwFXAGcAGYJmkjohYXeozBfgk8MaI2CLp8NQ+BvhHoA0IYHmad0v/b4qZmdXSyBn9ycDaiFgXEc8Ci4DpVX0+CFzVHeAR8VhqfyuwJCI2p2lLgGn9U7qZmTWikaAfD6wvPd6Q2sqOAY6RdIekuyVN68O8SLpIUkVSpaurq/Hqzcysrv66GDsCmAKcBswErpV0aKMzR8Q1EdEWEW3jxo3rp5LMzAwaC/qNwITS46NSW9kGoCMitkfEw8CDFMHfyLxmZjaAGgn6ZcAUSZMljQRmAB1VfW6lOJtH0liKoZx1wGLgTEmjJY0GzkxtZmY2SOp+6yYidkiaSxHQLcANEbFK0kKgEhEdPB/oq4GdwCciYhOApM9SvFkALIyIzQOxIWZmVpsiotk17KatrS0qlUqzyzAzG1YkLY+ItlrT/JuxZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbmWXOQW9mljkHvZlZ5hz0ZmaZc9CbWb8YMwakgb2NGdPsrRyeGgp6SdMkPSBpraRLakyfLalL0op0u7A0bWepvaM/izezoWPLFogY2NuWLc3eyuFpRL0OklqAq4AzgA3AMkkdEbG6qutNETG3xiKeiYgT9rpSMzPbI42c0Z8MrI2IdRHxLLAImD6wZZmZWX9pJOjHA+tLjzektmrnSrpP0i2SJpTaR0mqSLpb0jm1ViDpotSn0tXV1XDxZmZWX39djP0RMCkiXgUsAb5VmjYxItqA84EvSzq6euaIuCYi2iKibdy4cf1UkpmZQWNBvxEon6Efldp2iYhNEfHn9PA64KTStI3p5zrgNuA1e1GvmZn1USNBvwyYImmypJHADGC3b89IOqL08GxgTWofLWn/dH8s8Eag+iKumZkNoLrfuomIHZLmAouBFuCGiFglaSFQiYgO4COSzgZ2AJuB2Wn2VuBqSc9RvKlcVuPbOmZmNoAUEc2uYTdtbW1RqVSaXYaZ9ZFUfNd9uK9juJK0PF0PfQH/ZqyZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYc9GZmmXPQm5llzkFvZpY5B72ZWeYaCnpJ0yQ9IGmtpEtqTJ8tqUvSinS7sDRtlqSH0m1WfxZvZmb1jajXQVILcBVwBrABWCapIyJWV3W9KSLmVs07BvhHoA0IYHmad0u/VG9mZnU1ckZ/MrA2ItZFxLPAImB6g8t/K7AkIjancF8CTNuzUs3MbE80EvTjgfWlxxtSW7VzJd0n6RZJE/o4r5mZDZD+uhj7I2BSRLyK4qz9W32ZWdJFkiqSKl1dXf1UkpkNNmlgb7ZnGgn6jcCE0uOjUtsuEbEpIv6cHl4HnNTovGn+ayKiLSLaxo0b12jtZjaERPT9tifzWd81EvTLgCmSJksaCcwAOsodJB1Reng2sCbdXwycKWm0pNHAmanNzMwGSd1v3UTEDklzKQK6BbghIlZJWghUIqID+Iiks4EdwGZgdpp3s6TPUrxZACyMiM0DsB1mZtYDxRD7LNTW1haVSqXZZZjZIJA8HNNfJC2PiLZa0+qe0ZuZ7Y16F1F7mu43gP7joDezAeXAbj7/rRszs8w56M3MMuegNzPLnIPezCxzDnozs8w56M3MMuegNzPLnIPezCxzQ+5PIEjqAn7X7DoyMhZ4vNlFmPXAx2f/mRgRNf/875ALeutfkio9/f0Ls2bz8Tk4PHRjZpY5B72ZWeYc9Pm7ptkFmPXCx+cg8Bi9mVnmfEZvZpY5B72ZWeYc9EOIpHMkhaRjm12LDR+SdkpaIeleSb+S9IYG5nl6MGqrsd4Fki5uxrr3ZQ76oWUm0Jl+DghJLQO1bGuaZyLihIh4NfBJ4PPNLmioUmGfy719boOHKkkHAqcCc4AZqa1F0hclrZR0n6R5qf21ku5MZ3C/lHSQpNmSriwt78eSTkv3n5b0JUn3AqdI+gdJy9Jyr5GK/9op6RWSflo6Mzxa0o2Szikt97uSpg/SbrG+OxjYAsUxJek/03N5f63nrac+kiZJWiPpWkmrJP1E0gFp2guOk9T+iXRc3SfpM6V1zJf0oKRO4C9qFS3pLEm/kHRPWvZLS/V9I9V2n6RzU/u0tO57Jf1natvt00I6viel2wOSbgRWAhMkfU1SJW1budZar63bJZ1Q6tMp6dV7+Pw0R0T4NgRuwHuA69P9O4GTgL8FbgFGpPYxwEhgHfDa1HYwxf/+nQ1cWVrej4HT0v0AzitNG1O6/23grHT/F8A70v1RwIuBvwRuTW2HAA931+Pb0LgBO4EVwK+BJ4CTUvsI4OB0fyywlue/afd0b32AScAO4IQ07Wbggl6OkzMpviopihPIHwNvTsfx/anPwWn5F9fYhtGl2i4EvpTufwH4clW/ccB6YHL5eAYWlJdNEeqT0u054PXVrwGgBbgNeFUvr61Z3TUAxwCVZj/nfb35n4MPHTOBr6T7i9LjycDXI2IHQERslnQ88PuIWJbangRIJ+U92Ql8v/T4dEl/T/HiGwOsknQbMD4ifpiWuy31/bmkr0oaB5wLfL+7HhsynomIEwAknQLcKGkqReh+TtKbKYJuPPBS4NHSvD31AXg4Ilak+8uBSZIOosZxIulMirC/J/U/EJgCHAT8MCL+lPp19LANRwE3STqCInAfTu1vIX3CTevbIuks4PaIeDi1bW5gH/0uIu4uPT5P0kUUQX4E8EqKE6Jar63vAf9b0ieADwDfbGB9Q4qDfgiQNAb4K+B4SUFxlhHAsj4sZge7D8WNKt3fFhE707pGAV8F2iJivaQFVX1ruRG4gOIF9/4+1GSDLCLukjSW4qz37ennSRGxXdJveeFz/Z5e+vy51G8ncEAvqxbw+Yi4erdG6aMNln4F8M8R0ZGGHBc0OF9Zb6+BP5ZqmgxcTHHmvkXSN+nlNRARf5K0BJgOnEfxKWVY8Rj90PBO4NsRMTEiJkXEBIozmnuBD0kaAbveEB4AjpD02tR2UJr+W+AESS+SNAE4uYd1dR/Qj6u4LvBOgIh4CtjQPR4vaX9JL059vwl8NPVb3W9bbf1OxTe2WoBNFENtj6UAPx2YWGOWRvrs0stxshj4QDqmkDRe0uHA7cA5kg5InwbO6mHRhwAb0/1ZpfYlwIdL2zcauBt4cwrs7tcFFK+BE1PbiRSfiGs5mCL4n0jXAt6W2nt6bQFcB/wLsCwitvSw3CHLZ/RDw0yKsciy7wOtwCPAfZK2A9dGxJWS3g1ckS6OPUPx8fYOijeH1cAa4Fe1VhQRWyVdSzF++Si7f2p4L3C1pIXAduBdwLqI+IOkNcCt/bGx1u8OkLQi3RcwKyJ2Svou8CNJ9wMVijH8ao30qfaC4yQifiKpFbgrDSM+TTGm/ytJN1GctDxGz59SFwDfk7QF+BnPh/Q/AVdJWknxqeIzEfGDNOzyAxXfoHkMOIPiNfM+SasoriM8WGtFEXGvpHvStq6neO0QEc/28Np6OiKWS3oS+EYD+2fI8Z9AsLrSGdv9wIkR8USz6zEbbJKOpLhoe2xEPNfkcvrMQzfWK0lvofiEcIVD3vZFkt5H8Qlh/nAMefAZvZlZ9nxGb2aWOQe9mVnmHPRmZplz0JuZZc5Bb2aWuf8PQogp3tAUYmgAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "metrics.plot.box(color='blue')\n",
    "_ = plt.title(\"accuracy and Balanced accuracy metrics\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2849bf2b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:env_etl]",
   "language": "python",
   "name": "conda-env-env_etl-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
